name: nf-hello CI
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    name: Build nf-hello
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        java_version: [17, 21]
        nextflow_version: ['24.10']

    steps:
      - name: Environment
        run: env | sort

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true

      - name: Setup Java ${{ matrix.java_version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{matrix.java_version}}
          architecture: x64
          distribution: 'temurin'

      - name: Unit tests
        run: make test
        env:
          GRADLE_OPTS: '-Dorg.gradle.daemon=false'

      - name: Setup Nextflow ${{ matrix.nextflow_version }}
        uses: nf-core/setup-nextflow@b9f764e8ba5c76b712ace14ecbfcef0e40ae2dd8 # v1
        with:
          version: "${{ matrix.nextflow_version }}"

      - name: Install
        run: make install

      - name: Test
        run: nextflow run validation/ -plugins nf-hello@0.6.0
